// These variables will be injected into a page that will use them.
/* eslint no-unused-vars: "off" */
// Const won't work here, only var.
/* eslint no-var: "off" */

var nodes = [
  {
    id: 0,
    label: "Legitimate",
    title: "Legitimate",
    value: 4,
    group: 0,
	x: 500,
	y: 0,
  },
  {
    id: 1,
    label: "Phishing",
    title: "Phishing",
    value: 4,
    group: 1,
	x: -500,
	y: 0,
  },
  {
    id: 2,
    label: "Has TLS or SSL",
    title: "Has TLS or SSL",
    value: 3,
    group: 2,
	x: 0,
	y: 0,
  },
  {
    id: 3,
    label: "<= 43 Characters",
    title: "<= 43 Characters",
    value: 3,
    group: 2,
	x: 0,
	y: 400,
  },
  {
    id: 4,
    label: "Has Hyphens",
    title: "Has Hyphens",
    value: 3,
    group: 2,
	x: -200,
	y: -100,
  },
  {
    id: 5,
    label: "> 43 Characters",
    title: "> 43 Characters",
    value: 3,
    group: 2,
	x: -400,
	y: 400,
  },
  {
    id: 6,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 400,
	y: 300,
  },
  {
    id: 7,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 425,
	y: 300,
  },
  {
    id: 8,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 450,
	y: 300,
  },
  {
    id: 9,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 450,
	y: 325,
  },
  {
    id: 10,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 250,
	y: 150,
  },
  {
    id: 11,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 275,
	y: 150,
  },
  {
    id: 12,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 275,
	y: 175,
  },
  {
    id: 13,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 250,
	y: 175,
  },
  {
    id: 14,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: 225,
	y: 175,
  },
  {
    id: 15,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -200,
	y: 150,
  },
  {
    id: 16,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -225,
	y: 175,
  },
  {
    id: 17,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -250,
	y: 175,
  },
  {
    id: 18,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -275,
	y: 175,
  },
  {
    id: 19,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -225,
	y: 150,
  },
  {
    id: 20,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -250,
	y: 150,
  },
  {
    id: 21,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -275,
	y: 150,
  },
  {
    id: 22,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -450,
	y: 250,
  },
  {
    id: 23,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -475,
	y: 250,
  },
  {
    id: 24,
    label: "URL",
    title: "URL",
    value: 2,
    group: 3,
	x: -500,
	y: 250,
  },
];
// create an array with edges
var edges = [
  { from: 6, to: 0, label: "Classification", arrows: "to" },
  { from: 6, to: 3, label: "Characteristic", arrows: "to" },
  { from: 7, to: 0, arrows: "to" },
  { from: 7, to: 3, arrows: "to" },
  { from: 8, to: 0, arrows: "to" },
  { from: 8, to: 3, arrows: "to" },
  { from: 9, to: 0, arrows: "to" },
  { from: 9, to: 3, arrows: "to" },
  { from: 10, to: 0, label: "Classification", arrows: "to" },
  { from: 10, to: 3, label: "Characteristic", arrows: "to" },
  { from: 10, to: 2, label: "Characteristic", arrows: "to" },
  { from: 11, to: 0, arrows: "to" },
  { from: 11, to: 3, arrows: "to" },
  { from: 11, to: 2, arrows: "to" },
  { from: 12, to: 0, arrows: "to" },
  { from: 12, to: 3, arrows: "to" },
  { from: 12, to: 2, arrows: "to" },
  { from: 11, to: 2, arrows: "to" },
  { from: 13, to: 0, arrows: "to" },
  { from: 13, to: 3, arrows: "to" },
  { from: 13, to: 2, arrows: "to" },
  { from: 14, to: 0, arrows: "to" },
  { from: 14, to: 3, arrows: "to" },
  { from: 14, to: 2, arrows: "to" },
  { from: 15, to: 1, arrows: "to" },
  { from: 15, to: 3, label: "Characteristic", arrows: "to" },
  { from: 15, to: 2, label: "Characteristic", arrows: "to" },
  { from: 15, to: 4, label: "Characteristic", arrows: "to" },
  { from: 16, to: 1, arrows: "to" },
  { from: 16, to: 3, arrows: "to" },
  { from: 17, to: 5, label: "Characteristic", arrows: "to" },
  { from: 17, to: 1, label: "Classification", arrows: "to" },
  { from: 17, to: 2, arrows: "to" },
  { from: 18, to: 5, arrows: "to" },
  { from: 18, to: 1, arrows: "to" },
  { from: 18, to: 2, arrows: "to" },
  { from: 19, to: 1, arrows: "to" },
  { from: 19, to: 2, arrows: "to" },
  { from: 19, to: 5, arrows: "to" },
  { from: 19, to: 4, arrows: "to" },
  { from: 20, to: 1, arrows: "to" },
  { from: 20, to: 2, arrows: "to" },
  { from: 20, to: 5, arrows: "to" },
  { from: 20, to: 4, arrows: "to" },
  { from: 21, to: 1, arrows: "to" },
  { from: 21, to: 2, arrows: "to" },
  { from: 21, to: 5, arrows: "to" },
  { from: 21, to: 4, arrows: "to" },
  { from: 22, to: 1, label: "Classification", arrows: "to" },
  { from: 22, to: 5, label: "Characteristic", arrows: "to" },
  { from: 23, to: 1, arrows: "to" },
  { from: 23, to: 5, arrows: "to" },
  { from: 24, to: 1, arrows: "to" },
  { from: 24, to: 5, arrows: "to" },
];
